---
name: Iris Build
author: Christian Sargusingh
description: Builds iris-incuvers core20 snap for arm64.
runs:
  using: "composite"
  steps:
    - working-directory: ${{ github.action_path }}/lxd
      run: build.sh
      shell: bash
# runs:
#   using: docker
#   image: docker/Dockerfile
